# https://docs.travis-ci.com/user/reference/overview/#linux
dist: bionic

language: php

cache:
  directories:
    - "$HOME/.composer/cache"

php:
  # giacocorsiglia/stubs-generator does not support PHP 7.0
  - "7.1"
  - "7.2"
  - "7.3"
  - "7.4"

before_install:
  - |
    phpenv config-rm xdebug.ini
  - |
    composer validate --strict

install:
  - |
    composer update --no-interaction
  - |
    wget -nv -O "source/composer.lock" "https://github.com/wp-cli/wp-cli-bundle/raw/v$(jq -r '."version"' source/composer.json)/composer.lock"
    composer --working-dir=source/ install --no-interaction

script:
  - |
    bash -x ./generate.sh
  - |
    php -l wp-cli-stubs.php
  - |
    php -l wp-cli-commands-stubs.php
  - |
    php -l wp-cli-i18n-stubs.php
  - |
    git diff --exit-code
  - |
    php -r 'require "vendor/php-stubs/wordpress-stubs/wordpress-stubs.php"; require "wp-cli-stubs.php"; require "wp-cli-commands-stubs.php"; require "wp-cli-i18n-stubs.php";'
